# Generated by Django 4.0 on 2021-12-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('sal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DF',
            fields=[
                ('dname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
            ],
        ),
    ]
